# -*- coding: utf-8 -*-
"""codealpha.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1-kcwAhx7WNUloI4pJ79iHQYgNbO3ZDuq
"""

pip install requests

from google.cloud import translate_v2 as translate
import os

class SimpleTranslator:
    def __init__(self):
        # Initialize the Google Translate client
        self.client = translate.Client()

    def translate_text(self, text, target_language='en'):
        """
        Translate text to the target language.

        Args:
            text (str): The text to be translated.
            target_language (str): The language code to translate the text into.

        Returns:
            str: Translated text.
        """
        try:
            result = self.client.translate(text, target_language=target_language)
            return result['translatedText']
        except Exception as e:
            print(f"An error occurred: {e}")
            return None

def main():
    # Create a SimpleTranslator instance
    translator = SimpleTranslator()

    # Sample text and target language
    text = input("Enter text to translate: ")
    target_language = input("Enter target language code (e.g., 'es' for Spanish): ")

    # Translate text
    translated_text = translator.translate_text(text, target_language)

    if translated_text:
        print(f"Translated Text: {translated_text}")

if __name__ == "__main__":
    main()